server:
  port: 8761

spring:
  application:
    name: discovery-server

#security:
#    user:
#      name: lakshay
#      password: lakshay

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false